import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import AttentionRow from "@/components/AttentionRow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Srebro Lepić",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AttentionRow label="Besplatna dostava na narudžbe iznad 49,00KM" />
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
